<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html lang="en">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <title></title>
        <meta name="description" content="" />
        <meta name="keywords" content="" />

        <link rel="stylesheet" type="text/css" href="/yui/reset/reset-min.css" />
        <link rel="stylesheet" type="text/css" href="/yui/fonts/fonts-min.css" />
        <link rel="stylesheet" type="text/css" href="/yui/button/assets/skins/sam/button.css" />
        <link rel="stylesheet" type="text/css" href="/yui/menu/assets/skins/sam/menu.css" />

        <link rel="stylesheet" type="text/css" href="/css/screen.css" />

        <script type="text/javascript" src="/yui/utilities/utilities.js"></script>
        <script type="text/javascript" src="/yui/container/container-min.js"></script>
        <script type="text/javascript" src="/yui/menu/menu-min.js"></script>
        <script type="text/javascript" src="/yui/button/button-min.js"></script>

        <script type="text/javascript" src="/js/index_buttons.js"></script>
        <script type="text/javascript" src="/js/overview_buttons.js"></script>
        <script type="text/javascript" src="/js/general.js"></script>
        <script type="text/javascript" src="/js/dynamic_tables.js"></script>
    </head>

    <body class="yui-skin-sam"><?php echo $this->adminMenuControl ?>

        <div class="title">Index of: menu items</div>

        <?php echo $this->flashMessages() ?>

        <?php if ($this->allowCreateItem) : ?>
        <div class="actions">
            <img src="/images/icons/add.png" alt="Add icon" />
            <a class="link-button" href="/item/create/from/menu/provisionalTo/Menu/provisionalBeneathMenuItemId/0">Create new at top level</a>
            <!--<input type="button" id="btn_add_at_top_level_set" value="Create new ... at top level" />-->
            <?php //echo $this->createAtTopLevelDropdown ?>
        </div>
        <?php endif; ?>

        </div><!-- End top area -->

        <div id="stage"><!-- Start stage area -->

            <table class="table">
                <thead>
                    <tr>
                        <th>&nbsp;</th>
                        <th colspan="10">Actions</th>
                    </tr>
                </thead>
                <tbody>
                    <?php if ($this->menuItems) : ?>
                    <?php echo $this->partialLoop('menu/_menu-item.phtml', $this->menuItems) ?>
                    <?php else : ?>
                    <tr class="odd"><td width="100%">Empty result set</td><td colspan="10">&nbsp;</td></tr>
                    <?php endif; ?>
                </tbody>
            </table>

        </div><!-- End stage area -->

    </body>
</html>
