<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html lang="en">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <title></title>
        <meta name="description" content="" />
        <meta name="keywords" content="" />

        <link rel="stylesheet" type="text/css" href="/yui/reset/reset-min.css" />
        <link rel="stylesheet" type="text/css" href="/yui/fonts/fonts-min.css" />
        <link rel="stylesheet" type="text/css" href="/yui/button/assets/skins/sam/button.css" />
        <link rel="stylesheet" type="text/css" href="/yui/menu/assets/skins/sam/menu.css" />

        <link rel="stylesheet" type="text/css" href="/css/screen.css" />

        <script type="text/javascript" src="/yui/utilities/utilities.js"></script>
        <script type="text/javascript" src="/yui/container/container-min.js"></script>
        <script type="text/javascript" src="/yui/menu/menu-min.js"></script>
        <script type="text/javascript" src="/yui/button/button-min.js"></script>

        <script type="text/javascript" src="/js/buttons.js"></script>
        <script type="text/javascript" src="/js/general.js"></script>
        <script type="text/javascript" src="/js/dynamic_tables.js"></script>
    </head>

    <body class="yui-skin-sam">

        <div id="top"><!-- Start top area -->

            <div class="title">Create: block</div>
            <?php echo $this->flashMessages() ?>
            <div class="info"><img src="/images/required_star.png" alt="Required"> indicates required field</div>

        </div><!-- End top area -->

        <?php
        $form = $this->form;
        $form->render();
        ?>

        <form<?php foreach ($form->getAttribs() as $key => $value) : ?> <?php echo $key ?>="<?php echo $value ?>"<?php endforeach; ?>>

            <?php echo $this->decorateFormElement($form->from) ?>
            <?php echo $this->decorateFormElement($form->token) ?>

            <div id="stage"><!-- Start stage area -->

                <div class="white-box"><!-- Start fieldset -->
                    <div class="white-box-rounded-corner-top"><div></div></div>
                    <div class="white-box-content">
                        <div class="white-box-title">Settings</div>

                        <?php echo $this->decorateFormElement($form->name) ?>
                        <?php echo $this->decorateFormElement($form->typeId) ?>

                    </div>
                </div><!-- End fieldset -->

            </div><!-- End stage area -->

            <div class="submit-area">

                <div class="form-element">
                    <div class="form-inputs line-up">
                        <?php
                        $form->create->setAttrib('class', 'button');
                        echo $this->decorateFormElement($form->create, true) ?>
                    </div>
                </div>

            </div>

        </form>

    </body>
</html>
