<?php
$this->headLink()->appendStylesheet('/css/2col-large-left.css', 'screen');
$this->headLink()->appendStylesheet('/css/lime-green-colour-scheme.css', 'screen');
$this->layout()->title = 'Thank You';
$this->layout()->metaKeywords = '';
$this->layout()->metaDescription = '';
?>

            <section class="col first-col">
                <h1>Thank You</h1>
                <p>Your submission has been received</p>
            </section>
            <section class="col last-col">
                
            </section>
