<?php
$this->headLink()->appendStylesheet('/css/2col-large-left.css', 'screen');
if ($this->colourScheme) {
    $this->headLink()->appendStylesheet('/css/' . $this->colourScheme . '-colour-scheme.css', 'screen');
}
$this->layout()->title = $this->title;
$this->layout()->metaKeywords = $this->metaKeywords;
$this->layout()->metaDescription = $this->metaDescription;
$this->layout()->template = $this->templateName;
?>

            <section class="col first-col">
                <h1><?php echo $this->escape($this->title) ?></h1>
                <nav class="well">
                    <?php
                    echo $this->navigation()->menu()->renderMenu(null, array(
                        'ulId' => 'sitemap',
                    ));
                    ?>
                </nav>
            </section>
            <section class="col last-col">
                <?php foreach ((array) $this->rightColumn as $block) : echo $block; endforeach; ?>
            </section>
