<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html lang="en">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <title></title>
        <meta name="description" content="" />
        <meta name="keywords" content="" />

        <link rel="stylesheet" type="text/css" href="/yui/reset/reset-min.css" />
        <link rel="stylesheet" type="text/css" href="/yui/fonts/fonts-min.css" />
        <link rel="stylesheet" type="text/css" href="/yui/tabview/assets/skins/sam/tabview.css" />
        <link rel="stylesheet" type="text/css" href="/yui/button/assets/skins/sam/button.css" />
        <link rel="stylesheet" type="text/css" href="/yui/menu/assets/skins/sam/menu.css" />

        <link rel="stylesheet" type="text/css" href="/css/screen.css" />

        <script type="text/javascript" src="/yui/utilities/utilities.js"></script>
        <script type="text/javascript" src="/yui/tabview/tabview-min.js"></script>
        <script type="text/javascript" src="/yui/container/container-min.js"></script>
        <script type="text/javascript" src="/yui/menu/menu-min.js"></script>
        <script type="text/javascript" src="/yui/button/button-min.js"></script>
        <script type="text/javascript" src="/ckeditor/ckeditor.js"></script>
        <script type="text/javascript" src="/ckfinder/ckfinder.js"></script>

        <script type="text/javascript" src="/js/buttons.js"></script>
        <script type="text/javascript" src="/js/general.js"></script>
        <script type="text/javascript" src="/js/dynamic_tables.js"></script>
        <script type="text/javascript" src="/js/calendar.js"></script>
        <script type="text/javascript" src="/js/item_builder.js"></script>
    </head>

    <body class="yui-skin-sam" onLoad="<?php if ($this->preview) : ?>open_preview('<?php echo $this->escape($this->host) ?>/<?php echo $this->escape($this->itemName) ?>?preview=content')<?php endif; ?>">

        <div id="top"><!-- Start top area -->

            <div class="title">Edit<?php echo ($this->titleSuffix) ? ' ' . $this->escape(strtolower($this->titleSuffix)) : '' ?>:
            <?php echo $this->escape($this->typeName) ?> - <i><?php echo $this->escape($this->itemName) ?></i></div>
            <?php echo $this->flashMessages() ?>
            <div class="info"><img src="/images/required_star.png" alt="Required"> indicates required field</div>

        </div><!-- End top area -->

        <?php
        $form = $this->form;
        $form->render();
        ?>

        <form<?php foreach ($form->getAttribs() as $key => $value) : ?> <?php echo $key ?>="<?php echo $value ?>"<?php endforeach; ?>>

            <?php echo $this->decorateFormElement($form->from) ?>
            <?php echo $this->decorateFormElement($form->id) ?>
            <?php echo $this->decorateFormElement($form->partial) ?>
            <?php echo $this->decorateFormElement($form->token) ?>

            <div id="stage"><!-- Start stage area -->

                <div class="white-box"><!-- Start fieldset -->
                    <div class="white-box-rounded-corner-top"><div></div></div>
                    <div class="white-box-content">
                        <div class="white-box-title">Notes</div>
                        <p>
                            <?php if (empty($this->itemNotes)) : ?>
                            No notes found
                            <?php else : ?>
                            <?php foreach ($this->itemNotes as $note) : ?>
                            <?php echo $this->date($note->time, 'F j Y H:i') . ' - ' .
                            $this->escape($note->username) . ' - ' .
                            $this->escape($note->text) ?><br />
                            <?php endforeach; ?>
                            <?php endif; ?>
                        </p>
                    </div>
                </div><!-- End fieldset -->

                <div class="white-box"><!-- Start fieldset -->
                    <div class="white-box-rounded-corner-top"><div></div></div>
                    <div class="white-box-content">
                        <div class="white-box-title">Content</div>

                            <?php echo $this->decorateFormElement($form->navText) ?>
                            <?php if ($form->metaKeywords && $form->metaDescription) : ?>
                            <?php echo $this->decorateFormElement($form->metaKeywords) ?>
                            <?php echo $this->decorateFormElement($form->metaDescription) ?>
                            <?php endif; ?>
                            <?php echo $this->decorateFormElement($form->title) ?>

                            <?php
                            $fieldsForm = $form->getSubForm('fields');
                            foreach ($fieldsForm->getElements() as $element) : ?>
                            <?php echo $this->decorateFormElement($element) ?>
                            <?php if (strpos($element->getAttrib('class'), 'wysiwyg') !== false) : ?>
                            <script type="text/javascript">
                                var editor = CKEDITOR.replace('<?php echo $element->getId() ?>', {
                                    width: 700,
                                    height: 300
                                });
                                CKFinder.setupCKEditor(editor, '/ckfinder/');
                            </script>
                            <?php endif; ?>
                            <?php endforeach; ?>

                            <?php
                            $partsForm = $form->getSubForm('parts');
                            $parts = $partsForm->getSubForms();
                            ?>

                            <?php if ($form->getMultipleParts()) : ?>
                            <div id="ib_container" class="ib-container yui-navset">

                                <p>Add <select class="ib-add-part-select">
                                        <option value="0" selected="selected">0</option>
                                        <?php for ($i = 1; $i <= 10; $i++) : ?>
                                        <option value="<?php echo $i ?>"><?php echo $i ?></option>
                                        <?php endfor; ?>
                                    </select>
                                    <?php echo $this->decorateFormElement($form->numNewParts) ?> parts</p>

                                <ul id="ib_list" class="ib-draglist yui-nav">
                                    <?php foreach ($parts as $part) : ?>
                                    <li id="ib_list_item<?php echo $part->getName() ?>" class="ib-draglist-item<?php if ($form->selectedPart->getValue() == $part->getName()) : ?> selected<?php endif; ?>"<?php if ($part->delete->getValue()) : ?> style="display: none;"<?php endif; ?>><a href="#tab<?php echo $part->getName() ?>"><em>&nbsp;</em></a></li>
                                    <?php endforeach; ?>
                                </ul>

                                <?php echo $this->decorateFormElement($form->selectedPart) ?>

                                <div class="yui-content">
                             <?php endif; ?>

                                    <?php foreach ($parts as $part) : ?>
                                    <div id="ib_part<?php echo $part->getName() ?>" class="ib-part">

                                        <?php if ($form->getMultipleParts()) : ?>
                                        <?php echo $this->decorateFormElement($part->orderBy) ?>
                                        <img class="ib-delete-part-icon" src="/images/icons/dustbin.png" alt="Dustbin icon" title="Delete part" />
                                        <?php echo $this->decorateFormElement($part->delete) ?>
                                        <?php endif; ?>

                                        <?php $count = 0; foreach ($part->getElements() as $element) : ?>
                                        <?php if ($element->getName() != 'orderBy'
                                                && $element->getName() != 'delete') : ?>
                                        <?php echo $this->decorateFormElement($element) ?>
                                        <?php if (strpos($element->getAttrib('class'), 'wysiwyg') !== false) : ?>
                                        <script type="text/javascript">
                                            var editor = CKEDITOR.replace('<?php echo $element->getId() ?>', {
                                                width: 700,
                                                height: 300
                                            });
                                            CKFinder.setupCKEditor(editor, '/ckfinder/');
                                        </script>
                                        <?php endif; ?>
                                        <?php endif; ?>
                                        <?php $count++; endforeach; ?>

                                    </div>
                                    <?php endforeach; ?>

                            <?php if ($form->getMultipleParts()) : ?>
                                </div>
                            </div>
                            <?php endif; ?>
                        </div>

                    </div><!-- End fieldset -->
                </div><!-- End stage area -->

                <div class="submit-area">

                    <div class="form-element">
                        <div class="form-inputs line-up">
                            <?php if ($form->previewTemplateId) : ?>
                            <?php
                            $form->preview->setAttrib('class', 'menu-button');
                            echo $this->decorateFormElement($form->preview, true) ?>
                            <?php echo $this->decorateFormElement($form->previewTemplateId, true) ?>
                            <?php else : ?>
                            <?php
                            $form->preview->setAttrib('class', 'button');
                            echo $this->decorateFormElement($form->preview, true) ?>
                            <?php endif; ?>
                        </div>
                    </div>

                    <?php echo $this->decorateFormElement($form->note) ?>

                    <div class="form-element">
                        <div class="form-inputs line-up">
                            <?php
                            $form->save->setAttrib('class', 'button');
                            echo $this->decorateFormElement($form->save, true) ?>
                        </div>
                    </div>

                    <div class="form-element">
                        <div class="form-inputs line-up">
                            <?php
                            $form->publish->setAttrib('class', 'button');
                            echo $this->decorateFormElement($form->publish, true) ?>
                        </div>
                    </div>

                </div>

        </form>

    </body>
</html>
