<h3>Title:</h3>
<p><?php echo $this->escape($this->title) ?></p>
<h3>Image Number:</h3>
<p>#<?php echo $this->escape($this->imageNo) ?></p>
<h3>Price:</h3>
<p>&pound;<?php echo number_format($this->price, 2) ?></p>
<h3>Copyright:</h3>
<p>&copy; <?php echo $this->escape($this->copyright) ?></p>
<h3>Keywords:</h3>
<p><?php echo $this->escape($this->keywords) ?></p>
<h3>Description:</h3>
<p><?php echo $this->escape($this->description) ?></p>
<hr>
