<?php
switch ($this->type) {
    case 'category':
        $type = 'decade';
        break;
    case 'theme':
        $type = 'location';
        break;
    default:
        $type = 'subject';
}
?>
<tr class="<?php echo ($this->partialCounter % 2) ? 'odd' : 'even' ?>">
    <td><?php echo $type ?></td>
    <td><?php echo $this->escape($this->text) ?></td>
    <td><a href="/digital-gallery/edit-category/id/<?php echo $this->escape($this->id) ?>"><img src="/images/icons/edit.png" alt="Edit icon" title="Edit" /></a></td>
    <td><a href="/digital-gallery/delete-category/id/<?php echo $this->escape($this->id) ?>"><img src="/images/icons/dustbin.png" alt="Delete icon" title="Delete" /></a></td>
</tr>
