<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html lang="en">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <title></title>
        <meta name="description" content="" />
        <meta name="keywords" content="" />

        <link rel="stylesheet" type="text/css" href="/yui/reset/reset-min.css" />
        <link rel="stylesheet" type="text/css" href="/yui/fonts/fonts-min.css"/>
        <link rel="stylesheet" type="text/css" href="/yui/button/assets/skins/sam/button.css"/>
        <link rel="stylesheet" type="text/css" href="/yui/menu/assets/skins/sam/menu.css"/>

        <link rel="stylesheet" type="text/css" href="/css/screen.css" />

        <script type="text/javascript" src="/yui/utilities/utilities.js"></script>
        <script type="text/javascript" src="/yui/container/container-min.js"></script>
        <script type="text/javascript" src="/yui/menu/menu-min.js"></script>
        <script type="text/javascript" src="/yui/button/button-min.js"></script>

        <script type="text/javascript" src="/js/buttons.js"></script>
        <script type="text/javascript" src="/js/index_buttons.js"></script>
        <script type="text/javascript" src="/js/general.js"></script>
        <script type="text/javascript" src="/js/dynamic_tables.js"></script>
    </head>

    <body class="yui-skin-sam"><?php echo $this->adminMenuControl ?>

        <div class="title">Upload: image</div>

        <?php echo $this->flashMessages() ?>

        </div><!-- End top area -->

        <?php
        $form = $this->form;
        $form->render();
        ?>

        <form<?php foreach ($form->getAttribs() as $key => $value) : ?> <?php echo $key ?>="<?php echo $value ?>"<?php endforeach; ?>>

            <div id="stage"><!-- Start stage area -->

                <div class="white-box"><!-- Start fieldset -->
                    <div class="white-box-rounded-corner-top"><div></div></div>
                    <div class="white-box-content">
                        <div class="white-box-title">Upload</div>

                        <?php echo $this->decorateFormElement($form->token) ?>
                        <?php echo $this->decorateFormElement($form->title) ?>
                        <?php echo $this->decorateFormElement($form->keywords) ?>
                        <?php echo $this->decorateFormElement($form->description) ?>
                        <?php echo $this->decorateFormElement($form->imageNo) ?>
                        <?php //echo $this->decorateFormElement($form->credit) ?>
                        <?php echo $this->decorateFormElement($form->copyright) ?>
                        <?php echo $this->decorateFormElement($form->price) ?>
                        <?php echo $this->decorateFormElement($form->image) ?>
                        <?php echo $this->decorateFormElement($form->categories) ?>
                        <?php echo $this->decorateFormElement($form->themes) ?>
                        <?php echo $this->decorateFormElement($form->subjects) ?>

                    </div>
                </div><!-- End fieldset -->

            </div><!-- End stage area -->

            <div class="submit-area">
                <div class="form-element">
                    <div class="form-inputs line-up">
                        <?php
                        $form->upload->setAttrib('class', 'button');
                        echo $this->decorateFormElement($form->upload, true) ?>
                    </div>
                </div>
            </div>

        </form>

    </body>
</html>
