<tr class="<?php echo ($this->partialCounter % 2) ? 'odd' : 'even' ?>">

<td width="100%">
<div class="item-icon">
<img src="<?php echo $this->escape($this->typeIcon) ?>" alt="" title="<?php echo $this->escape($this->typeName) ?>" />
</div>
<div class="item-title"><em><?php echo $this->escape($this->name) ?></em></div>
<div class="item-detail">
Type: <em><?php echo $this->escape($this->typeName) ?></em><br />
Version: <em><?php echo $this->escape($this->workflowStatus) ?></em><br />
Authored by <em><?php echo $this->escape($this->authorUsername) ?></em> on <em><?php echo $this->date($this->authoredTime, 'l, F j, Y') ?></em> at <em><?php echo $this->date($this->authoredTime, 'H:i') ?></em></div></td>

<?php if ($this->controllerName != 'block') : ?>
<?php if ($this->workflowStatus == App_Service_Workflow::WORKFLOW_STATUS_NEW) : ?>
<td><input type="button" class="publishing-index-preview-menu-button workflow-preview" value="Preview" />
<select name="template_id">
<?php foreach ($this->availableTemplates as $template) : ?>
<option value="/<?php echo $this->escape($this->name) ?>?preview=publishing&templateId=<?php echo $this->escape($template->id) ?>">with <?php echo $this->escape($template->name) ?> template</option>
<?php endforeach; ?>
</select></td>
<?php else : ?>
<td><a class="link-button workflow-preview" onclick="open_preview('/<?php echo $this->escape($this->name) ?>?preview=publishing&contentId=<?php echo $this->escape($this->id) ?>')">Preview</a></td>
<?php endif; ?>
<?php else : ?>
<td>&nbsp;</td>
<?php endif; ?>

<td><img class="notes-icon clickable-icon" src="/images/icons/notes.png" alt="Notes icon" title="Notes" /><div class="notes">
<div class="hd">Notes</div>
<div class="bd"><p>
    <?php if (empty($this->notes)) : ?>
    No notes found
    <?php else : ?>
    <?php foreach ($this->notes as $note) : ?>
    <?php echo $this->date($note->time, 'F j Y H:i') . ' - ' .
    $this->escape($note->username) . ' - ' .
    $this->escape($note->text) ?><br />
    <?php endforeach; ?>
    <?php endif; ?>
    </p></div>
</div></td>

<td>
    <a id="<?php echo $this->escape($this->controllerName) ?>|<?php echo $this->escape($this->id) ?>" href="/workflow/send-back/moduleName/<?php echo $this->escape($this->controllerName) ?>/id/<?php echo $this->escape($this->id) ?>" class="workflow-send-back" title="Send back to author"><img src="/images/icons/arrow_left.png" alt="Arrow left icon" /></a>
</td>

<td>
    <a<?php if ($this->workflowStatus == App_Service_Workflow::WORKFLOW_STATUS_UPDATE) : ?> class="link-button workflow-publish" title="Publish update"<?php else : ?> class="workflow-publish" title="Go to publishing options"<?php endif; ?> href="/<?php echo $this->escape($this->controllerName) ?>/publish<?php if ($this->workflowStatus == App_Service_Workflow::WORKFLOW_STATUS_UPDATE) : ?>-update<?php endif; ?>/id/<?php echo $this->escape($this->id) ?>">
        <?php if ($this->workflowStatus == App_Service_Workflow::WORKFLOW_STATUS_UPDATE) : ?>
            Publish
        <?php else : ?>
            <img src="/images/icons/publish.png" alt="Publish icon" />
        <?php endif ?>
    </a>
</td>

<td>
    <a href="/workflow/publishing-delete/moduleName/<?php echo $this->escape($this->controllerName) ?>/id/<?php echo $this->escape($this->id) ?>" class="workflow-delete" title="Delete"><img src="/images/icons/dustbin.png" alt="Delete icon" /></a>
</td>

</tr>
