<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html lang="en">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <title></title>
        <meta name="description" content="" />
        <meta name="keywords" content="" />

        <link rel="stylesheet" type="text/css" href="/yui/reset/reset-min.css" />
        <link rel="stylesheet" type="text/css" href="/yui/fonts/fonts-min.css" />
        <link rel="stylesheet" type="text/css" href="/yui/menu/assets/skins/sam/menu.css" />
        <link rel="stylesheet" type="text/css" href="/yui/button/assets/skins/sam/button.css" />
        <link rel="stylesheet" type="text/css" href="/yui/container/assets/skins/sam/container.css" />

        <link rel="stylesheet" type="text/css" href="/css/screen.css" />

        <script type="text/javascript" src="/yui/utilities/utilities.js"></script>
        <script type="text/javascript" src="/yui/container/container-min.js"></script>
        <script type="text/javascript" src="/yui/menu/menu-min.js"></script>
        <script type="text/javascript" src="/yui/button/button-min.js"></script>

        <script type="text/javascript" src="/js/general.js"></script>
        <script type="text/javascript" src="/js/dynamic_tables.js"></script>
        <script type="text/javascript" src="/js/buttons.js"></script>
        <script type="text/javascript" src="/js/dialogs.js"></script>
    </head>

    <body class="yui-skin-sam"><?php echo $this->adminMenuControl ?>

        <div class="title">Index of: Publishing</div>

        <?php echo $this->flashMessages() ?>

        </div><!-- End top area -->

        <div id="stage"><!-- Start stage area -->

            <div id="send_back_dialog">
                <div class="hd">Send back to author</div>
                <div class="bd">
                    <form method="post" action="/workflow/send-back">
                        <input type="hidden" name="moduleName" value="" />
                        <input type="hidden" name="id" value="" />
                        <label for="notes" style="display: block;">Add a note:</label>
                        <textarea name="notes" style="width: 28em; height: 8em;"></textarea>
                    </form>
                </div>
            </div>

            <table class="table">
                <thead>
                    <tr>
                        <th>&nbsp;</th>
                        <th colspan="5">Actions</th>
                    </tr>
                </thead>
                <tbody>
                    <?php if ($this->publishingItems) : ?>
                    <?php echo $this->partialLoop('workflow/_publishing-item.phtml', $this->publishingItems) ?>
                    <?php else : ?>
                    <tr class="odd"><td width="100%">Empty result set</td><td colspan="5">&nbsp;</td></tr>
                    <?php endif; ?>
                </tbody>
            </table>

            <?php echo $this->paginationControl($this->paginator, 'Sliding', 'shared/_pagination.phtml'); ?>

        </div><!-- End stage area -->

    </body>
</html>
