<?php if ($this->pageCount): ?>
<nav class="pagination">
    <ul>
        <!-- Previous page link -->
        <?php if (isset($this->previous)): ?>
            <li>
                <a href="<?php echo $this->url(array_merge((array) $this->query, array('page' => $this->previous))); ?>">
                    &lt; Previous
                </a>
            </li>
        <?php else: ?>
            <li class="disabled">
                <span>
                    &lt; Previous
                </span>
            </li>
        <?php endif; ?>

        <!-- Numbered page links -->
        <?php foreach ($this->pagesInRange as $page): ?>
            <?php if ($page != $this->current): ?>
            <li>
                <a href="<?php echo $this->url(array_merge((array) $this->query, array('page' => $page))); ?>">
                    <?php echo $page; ?>
                </a>
            </li>
            <?php else: ?>
            <li class="disabled">
                <span>
                    <?php echo $page; ?>
                </span>
            </li>
            <?php endif; ?>
        <?php endforeach; ?>

        <!-- Next page link -->
        <?php if (isset($this->next)): ?>
            <li>
                <a href="<?php echo $this->url(array_merge((array) $this->query, array('page' => $this->next))); ?>">
                    Next &gt;
                </a>
            </li>
        <?php else: ?>
            <li class="disabled">
                <span>
                    Next &gt;
                </span>
            </li>
        <?php endif; ?>
    </ul>
</nav>
<?php endif; ?>
