<div class="yuimenu">
    <div class="bd">
        <ul class="first-of-type">
            <?php if ($this->allowCreateItem) : ?>
            <li class="yuimenuitem first-of-type">
                <a class="yuimenuitemlabel" href="/item/create/from/standalone/provisionalTo/Standalone">item</a>
            </li>
            <?php endif; ?>
            <?php if ($this->allowCreateForm) : ?>
            <li class="yuimenuitem<?php if (!$this->allowCreateItem) : ?> first-of-type<?php endif; ?>">
                <a class="yuimenuitemlabel" href="/form/create/from/standalone/provisionalTo/Standalone">form</a>
            </li>
            <?php endif; ?>
            <?php if ($this->allowCreateContainer) : ?>
            <li class="yuimenuitem<?php if (!$this->allowCreateItem && !$this->allowCreateForm) : ?> first-of-type<?php endif; ?>">
                <a class="yuimenuitemlabel" href="/container/create/from/standalone/provisionalTo/Standalone">container</a>
            </li>
            <?php endif; ?>
        </ul>
    </div>
</div>
