<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html lang="en">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <title></title>
        <meta name="description" content="" />
        <meta name="keywords" content="" />

        <link rel="stylesheet" type="text/css" href="/yui/reset/reset-min.css" />
        <link rel="stylesheet" type="text/css" href="/yui/fonts/fonts-min.css" />
        <link rel="stylesheet" type="text/css" href="/yui/button/assets/skins/sam/button.css" />
        <link rel="stylesheet" type="text/css" href="/yui/menu/assets/skins/sam/menu.css" />

        <link rel="stylesheet" type="text/css" href="/css/screen.css" />

        <script type="text/javascript" src="/yui/utilities/utilities.js"></script>
        <script type="text/javascript" src="/yui/container/container-min.js"></script>
        <script type="text/javascript" src="/yui/menu/menu-min.js"></script>
        <script type="text/javascript" src="/yui/button/button-min.js"></script>

        <script type="text/javascript" src="/js/index_buttons.js"></script>
        <script type="text/javascript" src="/js/general.js"></script>
        <script type="text/javascript" src="/js/dynamic_tables.js"></script>
    </head>

    <body class="yui-skin-sam"><?php echo $this->adminMenuControl ?>

        <div class="title">Index of: standalone content</div>

        <?php echo $this->flashMessages() ?>

        <?php if ($this->allowCreateItem) : ?>
        <div class="actions">
            <img src="/images/icons/add.png" alt="Add icon" />
            <a class="link-button" href="/item/create/from/standalone/provisionalTo/Standalone">Create new</a>
            <!--<input type="button" id="btn_author_set" value="Create new ..." />-->
            <?php //echo $this->createDropdown ?>
        </div>
        <?php endif; ?>

        </div><!-- End top area -->

        <div id="stage"><!-- Start stage area -->

            <table class="table">

                <thead>
                    <tr>
                        <th>&nbsp;</th>
                        <th colspan="7">Actions</th>
                    </tr>
                </thead>

                <tbody>

                    <?php if ($this->standaloneItems) : ?>
                        <?php echo $this->partialLoop('standalone/_standalone-item.phtml', $this->standaloneItems) ?>
                    <?php else : ?>
                        <tr class="odd"><td width="100%">Empty result set</td><td colspan="7">&nbsp;</td></tr>
                    <?php endif; ?>

                </tbody>
            </table>

            <?php echo $this->paginationControl($this->paginator, 'Sliding', 'shared/_pagination.phtml'); ?>

        </div><!-- End stage area -->

    </body>
</html>
